services:
  backend:
    image: sleiyah/nest-tasktick:latest
    container_name: tasktick-backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "3000:3000"
    restart: always
