name: CD

on:
    workflow_dispatch:
    workflow_run:
        workflows: [CI]
        types: [completed]
        branches: [main, develop]

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - name: Checkout code for deployment files
              uses: actions/checkout@v3

            - name: Copy deployment files to EC2
              uses: appleboy/scp-action@v1
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  source: "docker-compose.yaml,deploy.sh,.env"
                  target: "/home/${{ secrets.EC2_USER }}/"

            - name: Run deployment with migrations and seeds
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  script: |
                      # Make deployment script executable
                      chmod +x /home/${{ secrets.EC2_USER }}/deploy.sh

                      # Change to directory with deployment files
                      cd /home/${{ secrets.EC2_USER }}

                      # Run deployment script with migrations and seeds  
                      ./deploy.sh --with-migrations --with-seed
