name: CI

on:
    workflow_dispatch:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_KEY }}

            - name: Build backend Docker image
              working-directory: nest-tasktick
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nest-tasktick:latest .

            - name: Push Nest Image
              run: docker push ${{ secrets.DOCKER_USERNAME }}/nest-tasktick:latest

    test:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_KEY }}

            - name: Pull backend image
              run: docker pull ${{ secrets.DOCKER_USERNAME }}/nest-tasktick:latest

            - name: Run tests in backend container
              run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/nest-tasktick:latest npm test -- --verbose

    push-react:
        needs: test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_KEY }}

            - name: Build frontend Docker image
              working-directory: react-tasktick
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-tasktick:latest .

            - name: Push React Image
              run: docker push ${{ secrets.DOCKER_USERNAME }}/react-tasktick:latest
              