name: CI

on:
  push:
    branches:  develop 
  pull_request:
    branches:  develop

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: nest-tasktick/package-lock.json
        
    - name: Install backend dependencies
      run: |
        cd nest-tasktick
        npm ci
        
    - name: Build backend
      run: |
        cd nest-tasktick
        npm run build
        
    - name: Run backend tests
      run: |
        cd nest-tasktick
        npm test
        
  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: react-tasktick/package-lock.json
        
    - name: Install frontend dependencies
      run: |
        cd react-tasktick
        npm ci
        
    - name: Build frontend
      run: |
        cd react-tasktick
        npm run build
        
    - name: Run frontend tests
      run: |
        cd react-tasktick
        npm test -- --passWithNoTests
      
  docker-build:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build backend Docker image
      run: |
        cd nest-tasktick
        docker build -t nest-tasktick:latest .
      
    - name: Build frontend Docker image
      run: |
        cd react-tasktick
        docker build -t react-tasktick:latest .